config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    get 'users/sign_out', to: 'devise/sessions#destroy', as: :sign_out
  end
 

  get 'splash', to: 'static_pages#splash'
  
  authenticated :user do
    root 'sections#index', as: :authenticated_root
  end

  unauthenticated do
    root 'static_pages#splash', as: :unauthenticated_root
  end

  resources :users do
    resources :sections do
      resources :payments
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :user
  has_many :section_payments, dependent: :destroy
  has_many :sections, through: :section_payments

  validates :name, presence: true
  validates :amount, presence: true, numericality: { greater_than: 0 }
  validates :user_id, presence: true
end

app/models/section.rb
class Section < ApplicationRecord
  belongs_to :user
  has_many :section_payments, dependent: :destroy
  has_many :payments, through: :section_payments

  has_one_attached :icon
  validates :name, presence: true
  validates :icon, presence: true
end

app/models/section_payment.rb
class SectionPayment < ApplicationRecord
  belongs_to :section
  belongs_to :payment
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :sections, foreign_key: :user_id, dependent: :destroy
  has_many :payments, foreign_key: :user_id, dependent: :destroy

  validates :name, presence: true, length: { maximum: 60 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_out_path_for(_resource_or_scope)
    splash_path
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  def show
    @current_user = current_user
    @section = @current_user.sections.find(params[:section_id])
    @payments = @section.payments
    @payment = @payments.find(params[:id])
  end

  def new
    @current_user = current_user
    @sections = @current_user.sections
    @section = @current_user.sections.find(params[:section_id])
    @payment = @section.payments.new
  end

  def create
    @current_user = current_user
    @payment_create = @current_user.payments.build(payment_params)
    if @payment_create.save
      @section_payments = SectionPayment.create(section_id: params[:section], payment_id: @payment_create.id)
      redirect_to "/users/#{current_user.id}/sections/"
      flash[:notice] = 'Successfully create'
    else
      flash[:alert] = 'An error occured'
    end
  end

  private

  def payment_params
    params.require(:payment).permit(:name, :amount)
  end
end

app/controllers/sections_controller.rb
class SectionsController < ApplicationController
  before_action :authenticate_user!
  def index
    @items = current_user.sections.includes(:payments)
    @total_amount = 0
    @items.each do |item|
      @total_amount += item.payments.sum(:amount)
    end
  end

  def show
    @current_user = current_user
    @section = @current_user.sections.find(params[:id])
    @payments = @section.payments
  end

  def new
    @current_user = current_user
    @section = Section.new
  end

  def create
    @create_section = current_user.sections.build(section_params)
    if @create_section.save
      flash[:notice] = 'You have created new category successfully'
      redirect_to user_sections_path(current_user)
    else
      flash[:alert] = 'Error occured while creating new category '
    end
  end

  private

  def section_params
    params.require(:section).permit(:name, :icon)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def splash
    # my splash page logic
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
    @user = current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/sections_helper.rb
module SectionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BudgetTrackerPro</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css" integrity="sha512-z3gLpd7yknf1YoNbCzqRKc4qyor8gaKU1qmn+CShxbuBusANI9QpRohGBreCFkKxLhei6S9CQXFEbbKuqLg0DA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
     <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
   
    <%= yield %>
    <% flash.each do |key, message| %>
    <div class="flash-message">
      <%= message %>
    </div>
    <% end %>
  </body>
</html>

app/views/payments/new.html.erb
<%= render partial: 'shared/head', locals: { back: "Back", back_path: user_signed_in? ? user_sections_path(current_user) : splash_path } %>
<%= render partial: 'shared/payment' %>

app/views/payments/show.html.erb
<section class="d-flex flex-column pb-2 item-show">
<%= render partial: 'shared/head', locals: { back: " back", back_path: user_section_path(current_user, @section) } %>
<div class="d-flex flex-row justify-content-between align-items-center p-2">
<h1 class="">Name:<%= @payment.name %></h1>
<h4 class="">Catogery: <%= @section.name %></h4>
</div>
<div class="item-image d-flex flex-column align-items-center justify-content-center">
<%= image_tag @section.icon, class: "img-fluid img-thumbnail" %>
<h4 class="pt-2 text-dark fs-3">Amount: <%=@payment.amount %>$</h4>
<span class="text-primary date pt-4"><b class="text-dark px-2">Date: </b><%= @payment.created_at.strftime('%B-%d-%Y') %></span>
</div>
</section>

app/views/sections/index.html.erb
<%= render partial: 'shared/head', locals: { back: "Back", back_path: user_signed_in? ? user_sections_path(current_user) : splash_path } %>

<div class="container-fluid bg-white p-3">


  <div class="group px-3 d-flex flex-column align-items-center">
     <div class="d-flex justify-content-end align-items-center mb-3">
    <h4 class="mb-0 mr-2 ms-3">Total Payment:</h4>
    <h4 class="mb-0 ml-3 mr-5"><b><%=   @total_amount %></b> $</h4>
  </div>
    <div class="card w-100">
      <ul class="list-group list-group-flush">
        <% @items.each do |item| %>
          <li class="list-group-item d-flex justify-content-between align-items-center">
            <div class="d-flex align-items-center">
              <% if item.icon.attached? %>
                <%= image_tag item.icon, class: "img-item rounded-circle me-2", style: "width: 40px; height: 40px;" %>
              <% end %>
              <h5><%= link_to item.name, user_section_path(current_user, id: item.id), class: "text-decoration-none text-primary mb-0" %></h5>
            </div>
            <div class="d-flex flex-column">
              <span class="fs-4 mb-1"><%= item.payments.map { |item| item.amount }.sum %> $</span>
              <span class="text-primary date">
                <b class="text-dark">Date:</b> <%= item.created_at.strftime('%B %d, %Y') %>
              </span>
            </div>
          </li>
        <% end %>
      </ul>
    </div>
  </div>

  <div class="d-flex justify-content-center mt-3">
    <%= render partial: 'shared/button', locals: { button_text: "Add New Section", button_path: new_user_section_path(current_user) }, button_class: "btn-lg" %>
  </div>
</div>

app/views/sections/new.html.erb
<!DOCTYPE html>
<html>
<body>
<%= render partial: 'shared/head', locals: { back: "Back", back_path: user_signed_in? ? user_sections_path(current_user) : splash_path } %>
  <div class="container">
<section class="group_form d-flex flex-column justify-content-center align-items-center">

<%= render partial: 'shared/section' %>
</section>
</div>
</body>
</html>

app/views/sections/show.html.erb
<%= render partial: 'shared/head', locals: { back: "Back", back_path: user_signed_in? ? user_sections_path(current_user) : splash_path } %>

<div class="container-fluid bg-white p-3">
  <div class="d-flex justify-content-center">
    <div class="w-100">
      <div class='top d-flex flex-column align-items-center p-3'>
        <h1 class="text-center text-dark mb-3">
          <%= image_tag @section.icon, class: "small-icon me-2", style: "width: 60px; height: 60px;" %>
          <%= @section.name %>
        </h1>
        <h2 class="text-center">Total: <%= @payments.map { |item| item.amount }.sum %> $</h2>
      </div>
      <div class="items-container p-3">
        <ul class="list-group list-group-flush">
          <% @payments.each do |payment| %>
            <li class="list-group-item d-flex justify-content-between align-items-center">
              <div class="fs-5">
                <%= link_to payment.name, user_section_payment_path(current_user, @section, payment.id), class: "text-decoration-none text-primary" %>
              </div>
              <div class="d-flex flex-column align-items-center">
                <h4 class="fs-5"><%= payment.amount %> $</h4>
                <span class="text-primary">
                  <b class="text-dark">Date:</b> <%= payment.created_at.strftime('%B %d, %Y') %>
                </span>
              </div>
            </li>
          <% end %>
        </ul>
      </div>
      <div class="d-flex justify-content-center mt-3">
        <%= render partial: 'shared/button', locals: { button_text: "Add New Payment", button_path: new_user_section_payment_path(current_user, @section) }, button_class: "btn-lg" %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_button.html.erb
<div class="d-flex justify-content-center mt-4">
  <%= link_to button_text, button_path, class: 'btn btn-success col-1.5 ' %>
</div>

app/views/shared/_head.html.erb
<header class="navbar navbar-expand-md navbar-light bg-primary">
  <div class="container">
    <div class="d-flex flex-row justify-content-between align-items-center">
      <%= link_to back, back_path, class: "text-light text-decoration-none fs-5" %>
      <a href="/" class="navbar-brand d-flex align-items-center">
      </a>
      <div class="d-flex align-items-center">
      </div>
    </div>
  </div>
</header>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-md navbar-light bg-primary">
  <div class="container">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item">
          <a class="nav-link text-white d-none d-md-inline" href="#"><i class="bi bi-bell"></i></a>
        </li>
        <li class="nav-item">
          <a class="nav-link text-white" href="#"><i class="bi bi-house-door"></i> Home</a>
        </li>
        <% if user_signed_in? %>
          <li class="nav-item">
            <a href="<%= destroy_user_session_path %>" class="nav-link text-white">Sign Out</a>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Sign In", new_user_session_path, class: "nav-link text-white" %>
          </li>
          <li class="nav-item">
            <%= link_to "Sign Up", new_user_registration_path, class: "nav-link text-white" %>
          </li>
        <% end %>
      </ul>
    </div>
    <a class="navbar-brand text-white text-center mx-auto" href="/">Transactions</a>
  </div>
</nav>

app/views/shared/_payment.html.erb
<div class="col-12 border d-flex flex-column align-items-center py-3 px-5">
  <div class="col-8">
    <h4 class="text-center text-dark fs-3">Make a Payment</h4>
  </div>
  <div class="d-flex justify-content-center align-items-center flex-column border rounded p-3 col-8">
    <%= form_with url: user_section_payments_path, method: :post, class: "my-form" do |form| %>
      <div class="mb-3">
        <%= form.label :name %>
        <%= form.text_field :name, name: 'payment[name]', class: "form-control form-control-lg" %>
      </div>

      <div class="mb-3">
        <%= form.label :amount %>
        <%= form.text_field :amount, name: 'payment[amount]', class: "form-control form-control-lg" %>
      </div>

      <div class="mb-3">
        <%= form.label :section %>
        <%= form.select :section, options_from_collection_for_select(@sections, 'id', 'name'), { prompt: "Select a section" }, class: "form-select form-control-lg" %>
      </div>

      <div class="mb-3 text-center">
        <%= form.submit "Submit", class: "btn btn-success btn-lg" %>
      </div>
    <% end %>
  </div>
</div>

app/views/shared/_section.html.erb
<div class="col-12 d-flex flex-column align-items-center p-5">
  <div class="col-8">
    <h1 class="text-center">Create a New Section</h1>
  </div>
  <div class="d-flex justify-content-center align-items-center flex-column border rounded p-3 col-8">
    <%= form_with model: [current_user, @section], class: 'my-form' do |form| %>
      <div class="mb-3">
        <%= form.label :name %>
        <%= form.text_field :name, class: 'form-control' %>
      </div>

      <div class="mb-3">
        <%= form.label :icon %>
        <%= form.file_field :icon, class: 'form-control' %>
      </div>

      <div class="mb-3 d-flex justify-content-center">
        <%= form.submit "Submit", class: 'btn btn-primary btn-lg' %>
      </div>
    <% end %>
  </div>
</div>

app/views/splash/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Budget Tracker Pro</title>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css">
</head>
<body>
  <div class="container text-center mt-5">
    <div class="row">
      <div class="col-12">
        <%= image_tag("logo.png", alt: "Budget Tracker Pro Logo", class: "img-fluid rounded-circle mt-4", style: "max-width: 150px;") %>
      </div>
    </div>
    <h5 class="display-6 mt-4">Welcome to the Budget Tracker Pro</h5>
    <div class="mt-4">
      <%= link_to 'LOG IN', new_user_session_path, class: "btn btn-primary btn-lg me-3" %>
      <%= link_to 'SIGN UP', new_user_registration_path, class: "btn btn-success btn-lg" %>
    </div>
  </div>
</body>
</html>

app/views/static_pages/splash.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Budget Tracker Pro</title>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css">
</head>
<body>
  <div class="container text-center mt-5">
    <div class="row">
      <div class="col-12">
        <%= image_tag("logo.png", alt: "Budget Tracker Pro Logo", class: "img-fluid rounded-circle mt-4", style: "max-width: 150px;") %>
      </div>
    </div>
    <h5 class="display-6 mt-4 fw-bold">Budget Tracker Pro</h5>
    <div class="mt-5">
      <%= link_to 'LOG IN', new_user_session_path, class: "btn btn-primary btn-lg me-3 rounded-pill" %>
      <%= link_to 'SIGN UP', new_user_registration_path, class: "btn btn-success btn-lg rounded-pill" %>
    </div>
  </div>
</body>
</html>